### ISSUE TITLE
CAP Operator randomly restarting causing OOMKilled events

### ISSUE THREAD

**Issue by roman-holic-sap** [SAP/cap-operator#69]
Hello, we are facing issue with OOMKilled events of cap-operator-controller (ref: cs-devops/cluster-setup/issues/679) and found out, that issue is most probably caused by random restarts/panics of cap-operator-controller.

After cap-operator-controller restarts, than it spawns lot of queue/requeue events of cap systems which cause OOMKilled event of cap-operator-controller container as it exceeds memory limits.

Please check above mentioned issue for reference.

**Comment by Pavan-SAP** [comment]
Hi Roman,
at first glance this is unrealted to the panics in our reconciliation and moreover we have panic recovery mechanicsm (caused during our reconcililation). There does seem to be some issues in your cluster w.r.t cache misses (listers); but I do not see a clear cause as of now.

**Comment by Pavan-SAP** [comment]
It turns out there were possible some n/w issues in the cluster that causes several controllers to be OOMKilled due to some potential inconsistencies in cache:
Trace[250651049]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.29.1/tools/cache/reflector.go:229
Trace[250651049]: ---"Objects listed" error:<nil> 14502ms (06:27:28.375)

This seems unrelated to the CAP Operator implementation as such, hence closing this issue here.
